apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-agent
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: helm-charts/charts/datadog
    repoURL: https://github.com/stzou/containers_sandbox.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: datadog.apiKeyExistingSecret
          value: datadog-secret
        - name: datadog.kubelet.tlsVerify
          value: 'false'
        - name: datadog.logs.containerCollectAll
          value: 'true'
  sources: []
  project: default
