apiVersion: v1
kind: Service
metadata:
  labels:
    app: notes-app
  name: notes-service
  namespace: notes
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: notes-app
