apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-root
  namespace: argocd  # The namespace where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/stzou/containers_sandbox.git
    targetRevision: HEAD
    path: datadog
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
